/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSecretsRouteImport } from './routes/_authed/secrets'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedServersIndexRouteImport } from './routes/_authed/servers.index'
import { Route as AuthedProjectsIndexRouteImport } from './routes/_authed/projects.index'
import { Route as AuthedServersServerIdRouteImport } from './routes/_authed/servers.$serverId'
import { Route as AuthedProjectsProjectIdRouteImport } from './routes/_authed/projects.$projectId'
import { Route as AuthedAppsAppIdRouteImport } from './routes/_authed/apps.$appId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSecretsRoute = AuthedSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServersIndexRoute = AuthedServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsIndexRoute = AuthedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServersServerIdRoute = AuthedServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsProjectIdRoute = AuthedProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppsAppIdRoute = AuthedAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/secrets': typeof AuthedSecretsRoute
  '/settings': typeof AuthedSettingsRoute
  '/apps/$appId': typeof AuthedAppsAppIdRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdRoute
  '/servers/$serverId': typeof AuthedServersServerIdRoute
  '/projects/': typeof AuthedProjectsIndexRoute
  '/servers/': typeof AuthedServersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/secrets': typeof AuthedSecretsRoute
  '/settings': typeof AuthedSettingsRoute
  '/apps/$appId': typeof AuthedAppsAppIdRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdRoute
  '/servers/$serverId': typeof AuthedServersServerIdRoute
  '/projects': typeof AuthedProjectsIndexRoute
  '/servers': typeof AuthedServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/secrets': typeof AuthedSecretsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/apps/$appId': typeof AuthedAppsAppIdRoute
  '/_authed/projects/$projectId': typeof AuthedProjectsProjectIdRoute
  '/_authed/servers/$serverId': typeof AuthedServersServerIdRoute
  '/_authed/projects/': typeof AuthedProjectsIndexRoute
  '/_authed/servers/': typeof AuthedServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/secrets'
    | '/settings'
    | '/apps/$appId'
    | '/projects/$projectId'
    | '/servers/$serverId'
    | '/projects/'
    | '/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/secrets'
    | '/settings'
    | '/apps/$appId'
    | '/projects/$projectId'
    | '/servers/$serverId'
    | '/projects'
    | '/servers'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/secrets'
    | '/_authed/settings'
    | '/_authed/apps/$appId'
    | '/_authed/projects/$projectId'
    | '/_authed/servers/$serverId'
    | '/_authed/projects/'
    | '/_authed/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/secrets': {
      id: '/_authed/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AuthedSecretsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/servers/': {
      id: '/_authed/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthedServersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/': {
      id: '/_authed/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthedProjectsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/servers/$serverId': {
      id: '/_authed/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof AuthedServersServerIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthedProjectsProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/$appId': {
      id: '/_authed/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AuthedAppsAppIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSecretsRoute: typeof AuthedSecretsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedAppsAppIdRoute: typeof AuthedAppsAppIdRoute
  AuthedProjectsProjectIdRoute: typeof AuthedProjectsProjectIdRoute
  AuthedServersServerIdRoute: typeof AuthedServersServerIdRoute
  AuthedProjectsIndexRoute: typeof AuthedProjectsIndexRoute
  AuthedServersIndexRoute: typeof AuthedServersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSecretsRoute: AuthedSecretsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedAppsAppIdRoute: AuthedAppsAppIdRoute,
  AuthedProjectsProjectIdRoute: AuthedProjectsProjectIdRoute,
  AuthedServersServerIdRoute: AuthedServersServerIdRoute,
  AuthedProjectsIndexRoute: AuthedProjectsIndexRoute,
  AuthedServersIndexRoute: AuthedServersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
